spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id : itinerary-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/public/itinerary/**
              filters:
                - RewritePath=/api/public/itinerary/(?<segment>.*), /api/public/itinerary/${segment}



            - id: booking-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/public/booking/**
              filters:
                - RewritePath=/api/public/booking/(?<segment>.*), /api/v1/booking/${segment}
                
